leproperties: Create build.prop file using systemd-tmpfiles
- Install leprop.conf to create /etc/build.prop at run-time using
systemd-tmpfiles.
- Set /etc/build.prop to belong to leprop user/group so that leprop.service can access it.

Resolves error:
Error: leprop-service[pid]: Persist File doesnt exist

Root cause:
ll.c FILE *fp = fopen(PROP_FILE_PERSIST_PATH, "w");

- leprop.service runs with user/group leprop
- leprop.service doesn't have root priviledges to modify build.prop (which is root attribute)
- Update properties of build.prop to allow leprop user/group to access it.

Change-Id: I8a698e749efd255e550ddde96ae87e0a4a3d7aeb